package main;

public class FrameReporteAgrupado extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameReporteAgrupado.class.getName());
  private ReporteController reporteController = new ReporteController();

  /**
   * Creates new form FrameReporteAgrupado
   */
  public FrameReporteAgrupado() {
    initComponents();
    cargarDatos();
    setLocationRelativeTo(null);
  }

  private void cargarDatos() {
    int[] resultado = reporteController.reporteAgrupadoInterfaz();
    labelConteoPDR.setText("" + resultado[0]);
    labelConteoENC.setText("" + resultado[1]);
    labelConteoCAT.setText("" + resultado[2]);
    labelConteoDOG.setText("" + resultado[3]);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelCabecera = new javax.swing.JPanel();
    labelReporte = new javax.swing.JLabel();
    panelPrincipal = new javax.swing.JPanel();
    labelConteoTipo = new javax.swing.JLabel();
    labelPDR = new javax.swing.JLabel();
    labelENC = new javax.swing.JLabel();
    labelConteoPDR = new javax.swing.JLabel();
    labelConteoENC = new javax.swing.JLabel();
    labelConteoEspecie = new javax.swing.JLabel();
    labelCAT = new javax.swing.JLabel();
    labelDOG = new javax.swing.JLabel();
    labelConteoCAT = new javax.swing.JLabel();
    labelConteoDOG = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    panelCabecera.setLayout(new java.awt.BorderLayout());

    labelReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelReporte.setText("REPORTES AGRUPADOS");
    panelCabecera.add(labelReporte, java.awt.BorderLayout.CENTER);

    labelConteoTipo.setText("Conteo por tipo");

    labelPDR.setText("Perdidos:");

    labelENC.setText("Encontrados:");

    labelConteoPDR.setText("0");

    labelConteoENC.setText("0");

    labelConteoEspecie.setText("Conteo por Especie");

    labelCAT.setText("Gatos:");

    labelDOG.setText("Perros:");

    labelConteoCAT.setText("0");

    labelConteoDOG.setText("0");

    javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
    panelPrincipal.setLayout(panelPrincipalLayout);
    panelPrincipalLayout.setHorizontalGroup(
      panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelPrincipalLayout.createSequentialGroup()
        .addGap(38, 38, 38)
        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelConteoTipo)
          .addGroup(panelPrincipalLayout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelPDR)
              .addComponent(labelENC))
            .addGap(31, 31, 31)
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelConteoENC)
              .addComponent(labelConteoPDR))))
        .addGap(44, 44, 44)
        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(labelConteoEspecie)
          .addGroup(panelPrincipalLayout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(labelDOG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelConteoDOG))
              .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(labelCAT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelConteoCAT)))))
        .addContainerGap(80, Short.MAX_VALUE))
    );
    panelPrincipalLayout.setVerticalGroup(
      panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelPrincipalLayout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelConteoTipo)
          .addComponent(labelConteoEspecie))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelPDR)
          .addComponent(labelConteoPDR)
          .addComponent(labelCAT)
          .addComponent(labelConteoCAT))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelENC)
          .addComponent(labelConteoENC)
          .addComponent(labelDOG)
          .addComponent(labelConteoDOG))
        .addContainerGap(45, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new FrameReporteAgrupado().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel labelCAT;
  private javax.swing.JLabel labelConteoCAT;
  private javax.swing.JLabel labelConteoDOG;
  private javax.swing.JLabel labelConteoENC;
  private javax.swing.JLabel labelConteoEspecie;
  private javax.swing.JLabel labelConteoPDR;
  private javax.swing.JLabel labelConteoTipo;
  private javax.swing.JLabel labelDOG;
  private javax.swing.JLabel labelENC;
  private javax.swing.JLabel labelPDR;
  private javax.swing.JLabel labelReporte;
  private javax.swing.JPanel panelCabecera;
  private javax.swing.JPanel panelPrincipal;
  // End of variables declaration//GEN-END:variables
}
