package main;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

public class FrameReporteGeneral extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameReporteGeneral.class.getName());
  DefaultTableModel tablaModel = new DefaultTableModel();
  private ReporteController reporteController = new ReporteController();

  /**
   * Creates new form FrameReporteGeneral
   */
  public FrameReporteGeneral() {
    addModeloTabla();
    initComponents();
    setLocationRelativeTo(null);
    limpiarLabelsValores();
    cargarDatos();
  }

  private void addModeloTabla() {
    tablaModel.addColumn("ID Reporte");
    tablaModel.addColumn("ID Reportante");
    tablaModel.addColumn("Reportante");
    tablaModel.addColumn("Fecha");
    tablaModel.addColumn("Zona");
    tablaModel.addColumn("Contacto");
    tablaModel.addColumn("Especie");
    tablaModel.addColumn("Color");
    tablaModel.addColumn("Señas");
    tablaModel.addColumn("Microchip");
    tablaModel.addColumn("Raza");
    tablaModel.addColumn("Talla");
    tablaModel.addColumn("Pelaje");
    tablaModel.addColumn("Esterelizado");
    tablaModel.addColumn("Collar");
  }

  private void cargarDatos() {
    poblarTabla(reporteController.reportes);
  }

  private void poblarTabla(List<Reporte> reportes) {
    tablaModel.setRowCount(0);
    for (Reporte r : reportes) {
      String idReporte = r.getId();
      String idReportante = r.getReportanteId();
      String reportante = r.getNombreCompleto();
      String fecha = r.getFecha();
      String zona = r.getZona();
      String contacto = r.getContacto();

      Mascota mascota = r.getMascota();
      String especie = mascota.getEspecie();
      String color = mascota.getColor();
      String sennas = mascota.getSennas();
      String microchip = mascota.getMicrochip();

      String raza = "";
      String talla = "";
      String pelaje = "";
      String esterelizado = "";
      String collar = "";

      if ("CAT".equals(r.getMascota().getEspecie())) {
        Gato gato = (Gato) mascota;
        raza = gato.getRaza();
        pelaje = gato.getTipoPelaje();
        if (gato.isEsterelizado()) {
          esterelizado = "Sí";
        } else {
          esterelizado = "No";
        }
      } else {
        Perro perro = (Perro) mascota;
        raza = perro.getRaza();
        talla = perro.getTalla();
        if (perro.isCollar()) {
          collar = "Sí";
        } else {
          collar = "No";
        }
      }

      String[] rowData = {idReporte, idReportante, reportante, fecha, zona, contacto, especie, color, sennas, microchip, raza, talla, pelaje, esterelizado, collar};
      tablaModel.addRow(rowData);
    }

  }

  private void limpiarLabelsValores() {
    labelReporteValor.setText("");
    labelCedulaValor.setText("");
    labelReportanteValor.setText("");
    labelFechaValor.setText("");
    labelZonaValor.setText("");
    labelContactoValor.setText("");
    labelEspecieValor.setText("");
    labelColorValor.setText("");
    labelSennasValor.setText("");
    labelMicrochipValor.setText("");
    labelRazaValor.setText("");
    labelTallaValor.setText("");
    labelPelajeValor.setText("");
    labelEsterelizadoValor.setText("");
    labelCollarValor.setText("");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelTitulo = new javax.swing.JPanel();
    labelTitulo = new javax.swing.JLabel();
    panelPrincipal = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaReportes = new javax.swing.JTable();
    panelInformacion = new javax.swing.JPanel();
    labelReporte = new javax.swing.JLabel();
    labelReporteValor = new javax.swing.JLabel();
    labelCedula = new javax.swing.JLabel();
    labelCedulaValor = new javax.swing.JLabel();
    labelReportante = new javax.swing.JLabel();
    labelReportanteValor = new javax.swing.JLabel();
    labelFecha = new javax.swing.JLabel();
    labelFechaValor = new javax.swing.JLabel();
    labelZona = new javax.swing.JLabel();
    labelZonaValor = new javax.swing.JLabel();
    labelContacto = new javax.swing.JLabel();
    labelContactoValor = new javax.swing.JLabel();
    labelEspecie = new javax.swing.JLabel();
    labelEspecieValor = new javax.swing.JLabel();
    labelColor = new javax.swing.JLabel();
    labelColorValor = new javax.swing.JLabel();
    labelSennas = new javax.swing.JLabel();
    labelSennasValor = new javax.swing.JLabel();
    labelMicrochip = new javax.swing.JLabel();
    labelMicrochipValor = new javax.swing.JLabel();
    labelRaza = new javax.swing.JLabel();
    labelRazaValor = new javax.swing.JLabel();
    labelTalla = new javax.swing.JLabel();
    labelTallaValor = new javax.swing.JLabel();
    labelPelaje = new javax.swing.JLabel();
    labelPelajeValor = new javax.swing.JLabel();
    labelEsterelizado = new javax.swing.JLabel();
    labelEsterelizadoValor = new javax.swing.JLabel();
    labelCollar = new javax.swing.JLabel();
    labelCollarValor = new javax.swing.JLabel();
    panelFinal = new javax.swing.JPanel();
    buttonSalir = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    panelTitulo.setLayout(new java.awt.BorderLayout());

    labelTitulo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelTitulo.setText("Reporte General de Mascotas");
    panelTitulo.add(labelTitulo, java.awt.BorderLayout.CENTER);

    panelPrincipal.setLayout(new java.awt.BorderLayout());

    tablaReportes.setModel(tablaModel);

    ListSelectionListener listener = new ListSelectionListener() {
      @Override
      public void valueChanged(ListSelectionEvent e){
        if (e.getValueIsAdjusting()){
          int fila = tablaReportes.getSelectedRow();
          String reporteID = (String) tablaModel.getValueAt(fila, 0);
          String cedula = (String) tablaModel.getValueAt(fila, 1);
          String nombre = (String) tablaModel.getValueAt(fila, 2);
          String fecha = (String) tablaModel.getValueAt(fila, 3);
          String zona = (String) tablaModel.getValueAt(fila, 4);
          String contacto = (String) tablaModel.getValueAt(fila, 5);
          String especie = (String) tablaModel.getValueAt(fila, 6);
          String color = (String) tablaModel.getValueAt(fila, 7);
          String sennas = (String) tablaModel.getValueAt(fila, 8);
          String microchip = (String) tablaModel.getValueAt(fila, 9);
          String raza = (String) tablaModel.getValueAt(fila, 10);
          String talla = (String) tablaModel.getValueAt(fila, 11);
          String pelaje = (String) tablaModel.getValueAt(fila, 12);
          String esterelizado = (String) tablaModel.getValueAt(fila, 13);
          String collar = (String) tablaModel.getValueAt(fila, 14);

          labelReporteValor.setText(reporteID);
          labelCedulaValor.setText(cedula);
          labelReportanteValor.setText(nombre);
          labelFechaValor.setText(fecha);
          labelZonaValor.setText(zona);
          labelContactoValor.setText(contacto);
          labelEspecieValor.setText(especie);
          labelColorValor.setText(color);
          labelSennasValor.setText(sennas);
          labelMicrochipValor.setText(microchip);
          labelRazaValor.setText(raza);
          labelTallaValor.setText(talla);
          labelPelajeValor.setText(pelaje);
          labelEsterelizadoValor.setText(esterelizado);
          labelCollarValor.setText(collar);
        }
      }
    };
    tablaReportes.getSelectionModel().addListSelectionListener(listener);
    jScrollPane1.setViewportView(tablaReportes);

    panelPrincipal.add(jScrollPane1, java.awt.BorderLayout.CENTER);

    labelReporte.setText("ID Reporte");

    labelReporteValor.setText("Reporte");

    labelCedula.setText("Cedula");

    labelCedulaValor.setText("Cedula");

    labelReportante.setText("Reportante");

    labelReportanteValor.setText("Reportante");

    labelFecha.setText("Fecha");

    labelFechaValor.setText("Fecha");

    labelZona.setText("Zona");

    labelZonaValor.setText("Zona");

    labelContacto.setText("Contacto");

    labelContactoValor.setText("Contacto");

    labelEspecie.setText("Especie");

    labelEspecieValor.setText("Especie");

    labelColor.setText("Color");

    labelColorValor.setText("Color");

    labelSennas.setText("Señas");

    labelSennasValor.setText("Señas");

    labelMicrochip.setText("Microchip");

    labelMicrochipValor.setText("Microchip");

    labelRaza.setText("Raza");

    labelRazaValor.setText("Raza");

    labelTalla.setText("Talla");

    labelTallaValor.setText("Talla");

    labelPelaje.setText("Pelaje");

    labelPelajeValor.setText("Pelaje");

    labelEsterelizado.setText("Esterelizado");

    labelEsterelizadoValor.setText("Esterelizado");

    labelCollar.setText("Collar");

    labelCollarValor.setText("Collar");

    javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
    panelInformacion.setLayout(panelInformacionLayout);
    panelInformacionLayout.setHorizontalGroup(
      panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelInformacionLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelInformacionLayout.createSequentialGroup()
            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelReporte)
              .addComponent(labelCedula))
            .addGap(26, 26, 26)
            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelCedulaValor)
              .addComponent(labelReporteValor)))
          .addGroup(panelInformacionLayout.createSequentialGroup()
            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelReportante)
              .addComponent(labelContacto))
            .addGap(24, 24, 24)
            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelContactoValor)
              .addComponent(labelReportanteValor)
              .addComponent(labelFechaValor)
              .addComponent(labelZonaValor)))
          .addComponent(labelFecha)
          .addComponent(labelZona))
        .addGap(114, 114, 114)
        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelInformacionLayout.createSequentialGroup()
            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelMicrochip)
              .addComponent(labelTalla))
            .addGap(18, 18, 18)
            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelTallaValor)
              .addComponent(labelMicrochipValor)))
          .addGroup(panelInformacionLayout.createSequentialGroup()
            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelInformacionLayout.createSequentialGroup()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(labelEspecie)
                  .addComponent(labelColor))
                .addGap(28, 28, 28)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(labelEspecieValor)
                  .addComponent(labelColorValor)))
              .addGroup(panelInformacionLayout.createSequentialGroup()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(labelSennas)
                  .addComponent(labelRaza))
                .addGap(39, 39, 39)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(labelRazaValor)
                  .addComponent(labelSennasValor))))
            .addGap(135, 135, 135)
            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelEsterelizado)
              .addComponent(labelPelaje)
              .addComponent(labelCollar))
            .addGap(18, 18, 18)
            .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelCollarValor)
              .addComponent(labelPelajeValor)
              .addComponent(labelEsterelizadoValor))))
        .addContainerGap(66, Short.MAX_VALUE))
    );
    panelInformacionLayout.setVerticalGroup(
      panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelInformacionLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelReporte)
          .addComponent(labelReporteValor)
          .addComponent(labelEspecie)
          .addComponent(labelEspecieValor)
          .addComponent(labelPelaje)
          .addComponent(labelPelajeValor))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelCedula)
          .addComponent(labelCedulaValor)
          .addComponent(labelColor)
          .addComponent(labelColorValor)
          .addComponent(labelEsterelizado)
          .addComponent(labelEsterelizadoValor))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelReportante)
          .addComponent(labelReportanteValor)
          .addComponent(labelRaza)
          .addComponent(labelRazaValor)
          .addComponent(labelCollar)
          .addComponent(labelCollarValor))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelContacto)
          .addComponent(labelContactoValor)
          .addComponent(labelSennas)
          .addComponent(labelSennasValor))
        .addGap(12, 12, 12)
        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelFecha)
          .addComponent(labelFechaValor)
          .addComponent(labelMicrochip)
          .addComponent(labelMicrochipValor))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelZona)
          .addComponent(labelZonaValor)
          .addComponent(labelTalla)
          .addComponent(labelTallaValor))
        .addContainerGap(7, Short.MAX_VALUE))
    );

    buttonSalir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    buttonSalir.setText("SALIR");
    buttonSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonSalirActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
    panelFinal.setLayout(panelFinalLayout);
    panelFinalLayout.setHorizontalGroup(
      panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFinalLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(buttonSalir)
        .addGap(29, 29, 29))
    );
    panelFinalLayout.setVerticalGroup(
      panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFinalLayout.createSequentialGroup()
        .addContainerGap(23, Short.MAX_VALUE)
        .addComponent(buttonSalir)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(panelFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(panelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed

      InterfazGrafica newframe = new InterfazGrafica();
      newframe.setVisible(true);

      this.dispose();
    }//GEN-LAST:event_buttonSalirActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new FrameReporteGeneral().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonSalir;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel labelCedula;
  private javax.swing.JLabel labelCedulaValor;
  private javax.swing.JLabel labelCollar;
  private javax.swing.JLabel labelCollarValor;
  private javax.swing.JLabel labelColor;
  private javax.swing.JLabel labelColorValor;
  private javax.swing.JLabel labelContacto;
  private javax.swing.JLabel labelContactoValor;
  private javax.swing.JLabel labelEspecie;
  private javax.swing.JLabel labelEspecieValor;
  private javax.swing.JLabel labelEsterelizado;
  private javax.swing.JLabel labelEsterelizadoValor;
  private javax.swing.JLabel labelFecha;
  private javax.swing.JLabel labelFechaValor;
  private javax.swing.JLabel labelMicrochip;
  private javax.swing.JLabel labelMicrochipValor;
  private javax.swing.JLabel labelPelaje;
  private javax.swing.JLabel labelPelajeValor;
  private javax.swing.JLabel labelRaza;
  private javax.swing.JLabel labelRazaValor;
  private javax.swing.JLabel labelReportante;
  private javax.swing.JLabel labelReportanteValor;
  private javax.swing.JLabel labelReporte;
  private javax.swing.JLabel labelReporteValor;
  private javax.swing.JLabel labelSennas;
  private javax.swing.JLabel labelSennasValor;
  private javax.swing.JLabel labelTalla;
  private javax.swing.JLabel labelTallaValor;
  private javax.swing.JLabel labelTitulo;
  private javax.swing.JLabel labelZona;
  private javax.swing.JLabel labelZonaValor;
  private javax.swing.JPanel panelFinal;
  private javax.swing.JPanel panelInformacion;
  private javax.swing.JPanel panelPrincipal;
  private javax.swing.JPanel panelTitulo;
  private javax.swing.JTable tablaReportes;
  // End of variables declaration//GEN-END:variables
}
