package main;

import java.awt.HeadlessException;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

public class FrameRegistroReporte extends javax.swing.JFrame {
  
  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameRegistroReporte.class.getName());
  private ReporteController reporteController = new ReporteController();

  /**
   * Creates new form FrameRegistroReporte
   */
  public FrameRegistroReporte() {
    initComponents();
    initPanelEspecie();
    setLocationRelativeTo(null);
  }
  
  private void initPanelEspecie() {
    panelGato.setVisible(true);
    panelPerro.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelTitulo = new javax.swing.JPanel();
    labelTitulo = new javax.swing.JLabel();
    separadorTitulo = new javax.swing.JSeparator();
    panelPrincipal = new javax.swing.JPanel();
    labelIdReporte = new javax.swing.JLabel();
    labelIdReporteEjemplo = new javax.swing.JLabel();
    textoReporteId = new javax.swing.JTextField();
    labelCedula = new javax.swing.JLabel();
    labelCedulaEjemplo = new javax.swing.JLabel();
    textoCedula = new javax.swing.JTextField();
    labelNombre = new javax.swing.JLabel();
    labelNombreEjemplo = new javax.swing.JLabel();
    textoNombre = new javax.swing.JTextField();
    labelTipoReporte = new javax.swing.JLabel();
    comboTipoReporte = new javax.swing.JComboBox<>();
    labelFecha = new javax.swing.JLabel();
    labelFechaEjemplo = new javax.swing.JLabel();
    textoFecha = new javax.swing.JTextField();
    labelZona = new javax.swing.JLabel();
    textoZona = new javax.swing.JTextField();
    labelContacto = new javax.swing.JLabel();
    separadorDatosReportante = new javax.swing.JSeparator();
    textoContacto = new javax.swing.JTextField();
    labelContactoEjemplo = new javax.swing.JLabel();
    panelEspecie = new javax.swing.JPanel();
    labelEspecie = new javax.swing.JLabel();
    comboEspecie = new javax.swing.JComboBox<>();
    labelColor = new javax.swing.JLabel();
    textoColor = new javax.swing.JTextField();
    labelSennas = new javax.swing.JLabel();
    textoSennas = new javax.swing.JTextField();
    labelMicrochip = new javax.swing.JLabel();
    textoMicrochip = new javax.swing.JTextField();
    separadorEspecie = new javax.swing.JSeparator();
    panelGato = new javax.swing.JPanel();
    labelGato = new javax.swing.JLabel();
    labelRazaGato = new javax.swing.JLabel();
    textoRazaGato = new javax.swing.JTextField();
    labelTipoPelajeGato = new javax.swing.JLabel();
    comboTipoPelajeGato = new javax.swing.JComboBox<>();
    labelEsterelizadoGato = new javax.swing.JLabel();
    comboEsterelizadoGato = new javax.swing.JComboBox<>();
    panelPerro = new javax.swing.JPanel();
    labelPerro = new javax.swing.JLabel();
    labelRazaPerro = new javax.swing.JLabel();
    textoRazaPerro = new javax.swing.JTextField();
    labelTallaPerro = new javax.swing.JLabel();
    comboTallaPerro = new javax.swing.JComboBox<>();
    labelCollarPerro = new javax.swing.JLabel();
    comboCollarPerro = new javax.swing.JComboBox<>();
    panelFinal = new javax.swing.JPanel();
    botonGuardar = new javax.swing.JButton();
    botonVolver = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    panelTitulo.setLayout(new java.awt.BorderLayout());

    labelTitulo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelTitulo.setText("Registar Mascota");
    panelTitulo.add(labelTitulo, java.awt.BorderLayout.CENTER);
    panelTitulo.add(separadorTitulo, java.awt.BorderLayout.PAGE_END);

    labelIdReporte.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    labelIdReporte.setText("ID Reporte");

    labelIdReporteEjemplo.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
    labelIdReporteEjemplo.setText("Formato del ID: REP- seguido de cuatro números");

    textoReporteId.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        textoReporteIdActionPerformed(evt);
      }
    });

    labelCedula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    labelCedula.setText("Número de cédula");

    labelCedulaEjemplo.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
    labelCedulaEjemplo.setText("Formato del ID: 1-1111-1111");

    labelNombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    labelNombre.setText("Nombre completo");

    labelNombreEjemplo.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
    labelNombreEjemplo.setText("Mínimo 7 caracteres");

    labelTipoReporte.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    labelTipoReporte.setText("Tipo de reporte");

    comboTipoReporte.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    comboTipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDR", "ENC" }));
    comboTipoReporte.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        comboTipoReporteActionPerformed(evt);
      }
    });

    labelFecha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    labelFecha.setText("Fecha del reporte");

    labelFechaEjemplo.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
    labelFechaEjemplo.setText("Formato dd/mm/yyyy (Dejar vacío para tomar hora actual)");

    labelZona.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    labelZona.setText("Escriba la zona donde ocurrio el evento");

    labelContacto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    labelContacto.setText("Telefono de Contacto");

    labelContactoEjemplo.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
    labelContactoEjemplo.setText("El formato debe ser: ####-####");

    javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
    panelPrincipal.setLayout(panelPrincipalLayout);
    panelPrincipalLayout.setHorizontalGroup(
      panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelPrincipalLayout.createSequentialGroup()
        .addComponent(separadorDatosReportante)
        .addContainerGap())
      .addGroup(panelPrincipalLayout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelPrincipalLayout.createSequentialGroup()
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelContacto)
              .addComponent(labelNombreEjemplo)
              .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labelIdReporte)
                .addComponent(labelFecha)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                  .addComponent(labelNombre)
                  .addGap(110, 110, 110))
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(textoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(textoReporteId, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(labelIdReporteEjemplo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
              .addComponent(labelFechaEjemplo)
              .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(43, 43, 43)
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(labelZona)
                  .addComponent(labelTipoReporte)
                  .addComponent(labelCedulaEjemplo)
                  .addComponent(labelCedula)
                  .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboTipoReporte, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                    .addComponent(textoCedula, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(textoZona, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))))
          .addGroup(panelPrincipalLayout.createSequentialGroup()
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(textoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(labelContactoEjemplo))
            .addGap(0, 0, Short.MAX_VALUE))))
    );
    panelPrincipalLayout.setVerticalGroup(
      panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelIdReporte)
          .addComponent(labelCedula))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelIdReporteEjemplo)
          .addComponent(labelCedulaEjemplo))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(textoReporteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(textoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelNombre)
          .addComponent(labelTipoReporte))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelNombreEjemplo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(comboTipoReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelFecha)
          .addComponent(labelZona))
        .addGap(5, 5, 5)
        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(textoZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(panelPrincipalLayout.createSequentialGroup()
            .addComponent(labelFechaEjemplo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(labelContacto)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelContactoEjemplo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(textoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(separadorDatosReportante, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(533, 533, 533))
    );

    labelEspecie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    labelEspecie.setText("Especie");

    comboEspecie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    comboEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAT", "DOG" }));
    comboEspecie.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        comboEspecieActionPerformed(evt);
      }
    });

    labelColor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    labelColor.setText("Color principal de la mascota");

    labelSennas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    labelSennas.setText("Señas particulares de la mascota");

    labelMicrochip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    labelMicrochip.setText("Microchip (opcional)");

    javax.swing.GroupLayout panelEspecieLayout = new javax.swing.GroupLayout(panelEspecie);
    panelEspecie.setLayout(panelEspecieLayout);
    panelEspecieLayout.setHorizontalGroup(
      panelEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelEspecieLayout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addGroup(panelEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelEspecieLayout.createSequentialGroup()
            .addComponent(labelSennas)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelMicrochip)
            .addGap(159, 159, 159))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEspecieLayout.createSequentialGroup()
            .addGroup(panelEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEspecieLayout.createSequentialGroup()
                .addComponent(textoSennas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoMicrochip, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(panelEspecieLayout.createSequentialGroup()
                .addGroup(panelEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(panelEspecieLayout.createSequentialGroup()
                    .addComponent(labelEspecie)
                    .addGap(234, 237, Short.MAX_VALUE))
                  .addGroup(panelEspecieLayout.createSequentialGroup()
                    .addComponent(comboEspecie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(77, 77, 77)))
                .addGroup(panelEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(textoColor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(labelColor))))
            .addGap(79, 79, 79))))
      .addComponent(separadorEspecie)
    );
    panelEspecieLayout.setVerticalGroup(
      panelEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelEspecieLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelEspecie)
          .addComponent(labelColor))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(comboEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(textoColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelSennas)
          .addComponent(labelMicrochip, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(textoSennas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(textoMicrochip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(separadorEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(8, Short.MAX_VALUE))
    );

    labelGato.setText("Gato");

    labelRazaGato.setText("Raza");

    textoRazaGato.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        textoRazaGatoActionPerformed(evt);
      }
    });

    labelTipoPelajeGato.setText("Tipo de Pelaje");

    comboTipoPelajeGato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CORTO", "LARGO" }));

    labelEsterelizadoGato.setText("Esterelizado");

    comboEsterelizadoGato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

    javax.swing.GroupLayout panelGatoLayout = new javax.swing.GroupLayout(panelGato);
    panelGato.setLayout(panelGatoLayout);
    panelGatoLayout.setHorizontalGroup(
      panelGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelGatoLayout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addGroup(panelGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelGatoLayout.createSequentialGroup()
            .addGroup(panelGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelEsterelizadoGato)
              .addComponent(labelRazaGato)
              .addComponent(labelGato)
              .addComponent(textoRazaGato, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(panelGatoLayout.createSequentialGroup()
            .addGroup(panelGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(comboTipoPelajeGato, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(labelTipoPelajeGato)
              .addComponent(comboEsterelizadoGato, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE))))
    );
    panelGatoLayout.setVerticalGroup(
      panelGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelGatoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelGato)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelRazaGato)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(textoRazaGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelTipoPelajeGato)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(comboTipoPelajeGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelEsterelizadoGato)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(comboEsterelizadoGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(29, 29, 29))
    );

    labelPerro.setText("Perro");

    labelRazaPerro.setText("Raza");

    labelTallaPerro.setText("Talla");

    comboTallaPerro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEQ", "MED", "GRA" }));

    labelCollarPerro.setText("Collar");

    comboCollarPerro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

    javax.swing.GroupLayout panelPerroLayout = new javax.swing.GroupLayout(panelPerro);
    panelPerro.setLayout(panelPerroLayout);
    panelPerroLayout.setHorizontalGroup(
      panelPerroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelPerroLayout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addGroup(panelPerroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(labelCollarPerro)
          .addComponent(labelTallaPerro)
          .addComponent(labelRazaPerro)
          .addComponent(labelPerro)
          .addComponent(textoRazaPerro)
          .addComponent(comboTallaPerro, 0, 200, Short.MAX_VALUE)
          .addComponent(comboCollarPerro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelPerroLayout.setVerticalGroup(
      panelPerroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelPerroLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelPerro)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelRazaPerro)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(textoRazaPerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelTallaPerro)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(comboTallaPerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelCollarPerro)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(comboCollarPerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    botonGuardar.setText("Guardar");
    botonGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonGuardarActionPerformed(evt);
      }
    });

    botonVolver.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    botonVolver.setText("Volver");
    botonVolver.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonVolverActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
    panelFinal.setLayout(panelFinalLayout);
    panelFinalLayout.setHorizontalGroup(
      panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFinalLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(botonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
          .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(20, 20, 20))
    );
    panelFinalLayout.setVerticalGroup(
      panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelFinalLayout.createSequentialGroup()
        .addContainerGap(9, Short.MAX_VALUE)
        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(botonVolver)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(panelEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addComponent(panelGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelPerro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(panelFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelGato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelPerro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(28, 28, 28))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
      InterfazGrafica interfazGraficaFrame = new InterfazGrafica();
      interfazGraficaFrame.setVisible(true);
      
      this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void comboTipoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoReporteActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoReporteActionPerformed

    private void comboEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEspecieActionPerformed
      // Mostrar paneles respecto a especie escogida
      String especieSeleccionada = comboEspecie.getSelectedItem().toString();
      
      if (especieSeleccionada.equals("CAT")) {
        panelGato.setVisible(true);
        panelPerro.setVisible(false);
      } else if (especieSeleccionada.equals("DOG")) {
        panelPerro.setVisible(true);
        panelGato.setVisible(false);
      } else {
        panelGato.setVisible(false);
        panelPerro.setVisible(false);
      }

      // Actualiza la interfaz
      panelPrincipal.revalidate();
      panelPrincipal.repaint();
    }//GEN-LAST:event_comboEspecieActionPerformed

  private void textoReporteIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoReporteIdActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_textoReporteIdActionPerformed

  private void textoRazaGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRazaGatoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_textoRazaGatoActionPerformed

  private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
    // Invocar método de guardar reporte
    Reporte reporte;
    Mascota mascota = null;
    List<String> especiesPermitidas = Arrays.asList("DOG", "CAT");
    List<String> pelajesPermitidos = Arrays.asList("CORTO", "LARGO");
    List<String> opcionesSiNo = Arrays.asList("Si", "No");

    // Validaciones
    String reporteID = InputController.inputReporteIdInterfaz(textoReporteId.getText());
    if (reporteID == null) {
      return;
    }
    if (!reporteController.existeId(reporteID)) {
      JOptionPane.showMessageDialog(null, "El ID de reporte " + reporteID + " ya existe, digite otro");
      return;
    }
    
    String cedula = InputController.inputIDInterfaz(textoCedula.getText());
    if (cedula == null) {
      return;
    }
    
    String nombre = InputController.inputStringMinimoInterfaz(7, textoNombre.getText(), "Nombre");
    if (nombre == null) {
      return;
    }
    
    String fecha = InputController.inputFechaInterfaz(textoFecha.getText());
    if (fecha == null) {
      return;
    }
    
    String zona = InputController.inputStringRangoInterfaz(textoZona.getText(), 1, 30, "Zona");
    if (zona == null) {
      return;
    }
    
    String contacto = InputController.inputTelefonoInterfaz(textoContacto.getText());
    if (contacto == null) {
      return;
    }
    
    String especie = InputController.inputRestrictInterfaz(especiesPermitidas, comboEspecie.getSelectedItem().toString());
    if (especie == null) {
      return;
    }
    
    String color = InputController.inputStringInterfaz(textoColor.getText(), "Color");
    if (color == null) {
      return;
    }
    
    String sennas = InputController.inputStringRangoInterfaz(textoSennas.getText(), 10, 100, "Señas");
    if (sennas == null) {
      return;
    }

    // No necesita validación
    String microchip = textoMicrochip.getText();

    // Crear mascota
    if ("CAT".equals(especie)) {
      String razaGato = InputController.inputStringInterfaz(textoRazaGato.getText(), "Raza del gato");
      if (razaGato == null) {
        return;
      }
      
      String tipoPelajeGato = InputController.inputRestrictInterfaz(pelajesPermitidos, comboTipoPelajeGato.getSelectedItem().toString());
      if (tipoPelajeGato == null) {
        return;
      }
      
      String esterelizadoGato = InputController.inputRestrictInterfaz(opcionesSiNo, comboEsterelizadoGato.getSelectedItem().toString());
      boolean esterelizadoGatoB = false;
      if (esterelizadoGato == null) {
        return;
      }
      
      if ("Si".equals(esterelizadoGato)) {
        esterelizadoGatoB = true;
      }
      mascota = new Gato(razaGato, tipoPelajeGato, esterelizadoGatoB, especie, color, sennas, microchip);
    }
    if ("DOG".equals(especie)) {
      
      String razaPerro = InputController.inputStringInterfaz(textoRazaPerro.getText(), "Raza del perro");
      if (razaPerro == null) {
        return;
      }
      
      List<String> tallasPermitidasPerro = Arrays.asList("PEQ", "MED", "GRA");
      String tallaPerro = InputController.inputRestrictInterfaz(tallasPermitidasPerro, comboTallaPerro.getSelectedItem().toString());
      if (tallaPerro == null) {
        return;
      }
      
      String collarPerro = InputController.inputRestrictInterfaz(opcionesSiNo, comboCollarPerro.getSelectedItem().toString());
      boolean collarPerroB = false;
      if (collarPerro == null) {
        return;
      }
      
      if ("Si".equals(collarPerro)) {
        collarPerroB = true;
      }
      mascota = new Perro(razaPerro, tallaPerro, collarPerroB, especie, color, sennas, microchip);
    }
    
    if ("PDR".equals(comboTipoReporte.getSelectedItem().toString())) {
      reporte = new ReportePerdida(reporteID, cedula, nombre, fecha, zona, contacto, mascota);
    } else {
      reporte = new ReporteEncontrada(reporteID, cedula, nombre, fecha, zona, contacto, mascota);
    }
    
    try {
      reporteController.crearReporte(reporte);
      JOptionPane.showMessageDialog(null, "Reporte guardado exitosamente");
      limpiarDatos();
    } catch (HeadlessException e) {
      JOptionPane.showMessageDialog(null, "Error al agregar el reporte. Error: " + e.getMessage());
    }
  }//GEN-LAST:event_botonGuardarActionPerformed
  
  private void limpiarDatos() {
    textoReporteId.setText("");
    textoCedula.setText("");
    textoNombre.setText("");
    textoFecha.setText("");
    textoZona.setText("");
    textoContacto.setText("");
    textoColor.setText("");
    textoSennas.setText("");
    textoMicrochip.setText("");
    textoRazaGato.setText("");
    textoRazaPerro.setText("");
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new FrameRegistroReporte().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonGuardar;
  private javax.swing.JButton botonVolver;
  private javax.swing.JComboBox<String> comboCollarPerro;
  private javax.swing.JComboBox<String> comboEspecie;
  private javax.swing.JComboBox<String> comboEsterelizadoGato;
  private javax.swing.JComboBox<String> comboTallaPerro;
  private javax.swing.JComboBox<String> comboTipoPelajeGato;
  private javax.swing.JComboBox<String> comboTipoReporte;
  private javax.swing.JLabel labelCedula;
  private javax.swing.JLabel labelCedulaEjemplo;
  private javax.swing.JLabel labelCollarPerro;
  private javax.swing.JLabel labelColor;
  private javax.swing.JLabel labelContacto;
  private javax.swing.JLabel labelContactoEjemplo;
  private javax.swing.JLabel labelEspecie;
  private javax.swing.JLabel labelEsterelizadoGato;
  private javax.swing.JLabel labelFecha;
  private javax.swing.JLabel labelFechaEjemplo;
  private javax.swing.JLabel labelGato;
  private javax.swing.JLabel labelIdReporte;
  private javax.swing.JLabel labelIdReporteEjemplo;
  private javax.swing.JLabel labelMicrochip;
  private javax.swing.JLabel labelNombre;
  private javax.swing.JLabel labelNombreEjemplo;
  private javax.swing.JLabel labelPerro;
  private javax.swing.JLabel labelRazaGato;
  private javax.swing.JLabel labelRazaPerro;
  private javax.swing.JLabel labelSennas;
  private javax.swing.JLabel labelTallaPerro;
  private javax.swing.JLabel labelTipoPelajeGato;
  private javax.swing.JLabel labelTipoReporte;
  private javax.swing.JLabel labelTitulo;
  private javax.swing.JLabel labelZona;
  private javax.swing.JPanel panelEspecie;
  private javax.swing.JPanel panelFinal;
  private javax.swing.JPanel panelGato;
  private javax.swing.JPanel panelPerro;
  private javax.swing.JPanel panelPrincipal;
  private javax.swing.JPanel panelTitulo;
  private javax.swing.JSeparator separadorDatosReportante;
  private javax.swing.JSeparator separadorEspecie;
  private javax.swing.JSeparator separadorTitulo;
  private javax.swing.JTextField textoCedula;
  private javax.swing.JTextField textoColor;
  private javax.swing.JTextField textoContacto;
  private javax.swing.JTextField textoFecha;
  private javax.swing.JTextField textoMicrochip;
  private javax.swing.JTextField textoNombre;
  private javax.swing.JTextField textoRazaGato;
  private javax.swing.JTextField textoRazaPerro;
  private javax.swing.JTextField textoReporteId;
  private javax.swing.JTextField textoSennas;
  private javax.swing.JTextField textoZona;
  // End of variables declaration//GEN-END:variables
}
