/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

public class InterfazGrafica extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafica.class.getName());

  /**
   * Creates new form InterfazGrafica
   */
  public InterfazGrafica() {
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ButtonOpcion1 = new javax.swing.JButton();
        ButtonOpcion2 = new javax.swing.JButton();
        ButtonOpcion3 = new javax.swing.JButton();
        ButtonOpcion4 = new javax.swing.JButton();
        ButtonOpcion5 = new javax.swing.JButton();
        ButtonOpcion6 = new javax.swing.JButton();
        ButtonOpcion7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("SISTEMA - REFUGIO \"HUELLAS FELICES\"");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("GESTOR DE REPORTES DE MASCOTAS");

        jLabel3.setText("=====================================================================================");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Haz clic en la opción del menú");

        ButtonOpcion1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ButtonOpcion1.setText("1. Registar mascota desaparecida");
        ButtonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOpcion1ActionPerformed(evt);
            }
        });

        ButtonOpcion2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ButtonOpcion2.setText("2. Consultar por ID/Especie/Zona");
        ButtonOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOpcion2ActionPerformed(evt);
            }
        });

        ButtonOpcion3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ButtonOpcion3.setText("3. Reporte General");
        ButtonOpcion3.setToolTipText("");
        ButtonOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOpcion3ActionPerformed(evt);
            }
        });

        ButtonOpcion4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ButtonOpcion4.setText("4. Reporte Agrupado");
        ButtonOpcion4.setToolTipText("");
        ButtonOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOpcion4ActionPerformed(evt);
            }
        });

        ButtonOpcion5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ButtonOpcion5.setText("5. Ver coincidencias");
        ButtonOpcion5.setToolTipText("");
        ButtonOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOpcion5ActionPerformed(evt);
            }
        });

        ButtonOpcion6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ButtonOpcion6.setText("6. Actualizar Reporte ");
        ButtonOpcion6.setToolTipText("");
        ButtonOpcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOpcion6ActionPerformed(evt);
            }
        });

        ButtonOpcion7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ButtonOpcion7.setText("7. Salir");
        ButtonOpcion7.setToolTipText("");
        ButtonOpcion7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOpcion7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonOpcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonOpcion5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonOpcion6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonOpcion7, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(ButtonOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonOpcion2)
                .addGap(18, 18, 18)
                .addComponent(ButtonOpcion3)
                .addGap(18, 18, 18)
                .addComponent(ButtonOpcion4)
                .addGap(18, 18, 18)
                .addComponent(ButtonOpcion5)
                .addGap(18, 18, 18)
                .addComponent(ButtonOpcion6)
                .addGap(18, 18, 18)
                .addComponent(ButtonOpcion7)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpcion1ActionPerformed
      Ventana1 newframe = new Ventana1();
      newframe.setVisible(true);

      this.dispose();
    }//GEN-LAST:event_ButtonOpcion1ActionPerformed

  private void ButtonOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpcion2ActionPerformed
    Frame_Consultas frameConsultas = new Frame_Consultas();
    frameConsultas.setVisible(true);

    this.dispose();
  }//GEN-LAST:event_ButtonOpcion2ActionPerformed

    private void ButtonOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpcion3ActionPerformed
        FrameReporteGeneral frameReporteGeneral = new FrameReporteGeneral(); 
        frameReporteGeneral.setVisible(true); 
        
        this.dispose();
    }//GEN-LAST:event_ButtonOpcion3ActionPerformed

    private void ButtonOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpcion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonOpcion4ActionPerformed

    private void ButtonOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpcion5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonOpcion5ActionPerformed

    private void ButtonOpcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpcion6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonOpcion6ActionPerformed

    private void ButtonOpcion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpcion7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonOpcion7ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new InterfazGrafica().setVisible(true));
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonOpcion1;
    private javax.swing.JButton ButtonOpcion2;
    private javax.swing.JButton ButtonOpcion3;
    private javax.swing.JButton ButtonOpcion4;
    private javax.swing.JButton ButtonOpcion5;
    private javax.swing.JButton ButtonOpcion6;
    private javax.swing.JButton ButtonOpcion7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
