/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

public class InterfazGrafica extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafica.class.getName());

  /**
   * Creates new form InterfazGrafica
   */
  public InterfazGrafica() {
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    botonRegistrarReporte = new javax.swing.JButton();
    botonConsultarReportes = new javax.swing.JButton();
    ButtonOpcion3 = new javax.swing.JButton();
    botonReporteAgrupado = new javax.swing.JButton();
    ButtonOpcion5 = new javax.swing.JButton();
    ButtonOpcion6 = new javax.swing.JButton();
    ButtonOpcion7 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel1.setText("SISTEMA - REFUGIO \"HUELLAS FELICES\"");

    jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel2.setText("GESTOR DE REPORTES DE MASCOTAS");

    jLabel3.setText("=====================================================================================");

    jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel4.setText("Haz clic en la opción del menú");

    botonRegistrarReporte.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    botonRegistrarReporte.setText("1. Registar mascota desaparecida");
    botonRegistrarReporte.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonRegistrarReporteActionPerformed(evt);
      }
    });

    botonConsultarReportes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    botonConsultarReportes.setText("2. Consultar por ID/Especie/Zona");
    botonConsultarReportes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonConsultarReportesActionPerformed(evt);
      }
    });

    ButtonOpcion3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    ButtonOpcion3.setText("3. Reporte General");
    ButtonOpcion3.setToolTipText("");
    ButtonOpcion3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ButtonOpcion3ActionPerformed(evt);
      }
    });

    botonReporteAgrupado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    botonReporteAgrupado.setText("4. Reporte Agrupado");
    botonReporteAgrupado.setToolTipText("");
    botonReporteAgrupado.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonReporteAgrupadoActionPerformed(evt);
      }
    });

    ButtonOpcion5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    ButtonOpcion5.setText("5. Ver coincidencias");
    ButtonOpcion5.setToolTipText("");
    ButtonOpcion5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ButtonOpcion5ActionPerformed(evt);
      }
    });

    ButtonOpcion6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    ButtonOpcion6.setText("6. Actualizar Reporte ");
    ButtonOpcion6.setToolTipText("");
    ButtonOpcion6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ButtonOpcion6ActionPerformed(evt);
      }
    });

    ButtonOpcion7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    ButtonOpcion7.setText("7. Salir");
    ButtonOpcion7.setToolTipText("");
    ButtonOpcion7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ButtonOpcion7ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(14, 14, 14))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(98, 98, 98)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel2))))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(336, 336, 336)
            .addComponent(jLabel4))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(322, 322, 322)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(botonConsultarReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(botonRegistrarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(ButtonOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(botonReporteAgrupado, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(ButtonOpcion5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(ButtonOpcion6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(ButtonOpcion7, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(129, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(44, 44, 44)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel4)
        .addGap(18, 18, 18)
        .addComponent(botonRegistrarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(botonConsultarReportes)
        .addGap(18, 18, 18)
        .addComponent(ButtonOpcion3)
        .addGap(18, 18, 18)
        .addComponent(botonReporteAgrupado)
        .addGap(18, 18, 18)
        .addComponent(ButtonOpcion5)
        .addGap(18, 18, 18)
        .addComponent(ButtonOpcion6)
        .addGap(18, 18, 18)
        .addComponent(ButtonOpcion7)
        .addContainerGap(120, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarReporteActionPerformed
      FrameRegistroReporte newframe = new FrameRegistroReporte();
      newframe.setVisible(true);

      this.dispose();
    }//GEN-LAST:event_botonRegistrarReporteActionPerformed

  private void botonConsultarReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarReportesActionPerformed
    Frame_Consultas frameConsultas = new Frame_Consultas();
    frameConsultas.setVisible(true);

    this.dispose();
  }//GEN-LAST:event_botonConsultarReportesActionPerformed

    private void ButtonOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpcion3ActionPerformed
      FrameReporteGeneral frameReporteGeneral = new FrameReporteGeneral();
      frameReporteGeneral.setVisible(true);

      this.dispose();
    }//GEN-LAST:event_ButtonOpcion3ActionPerformed

    private void botonReporteAgrupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteAgrupadoActionPerformed
      FrameReporteAgrupado frameReporteAgrupado = new FrameReporteAgrupado();
      frameReporteAgrupado.setVisible(true);

      this.dispose();
    }//GEN-LAST:event_botonReporteAgrupadoActionPerformed

    private void ButtonOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpcion5ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_ButtonOpcion5ActionPerformed

    private void ButtonOpcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpcion6ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_ButtonOpcion6ActionPerformed

    private void ButtonOpcion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpcion7ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_ButtonOpcion7ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new InterfazGrafica().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton ButtonOpcion3;
  private javax.swing.JButton ButtonOpcion5;
  private javax.swing.JButton ButtonOpcion6;
  private javax.swing.JButton ButtonOpcion7;
  private javax.swing.JButton botonConsultarReportes;
  private javax.swing.JButton botonRegistrarReporte;
  private javax.swing.JButton botonReporteAgrupado;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
